### ISSUE TITLE
使用 Go 重写

### ISSUE THREAD

**Issue by knight42** [ustclug/Yuki#13]
高优先级:
* [x] 读取程序配置
* [x] 更新 repo 配置时，对请求体进行类型校验
* [x] 程序启动时以及同步结束后更新 Meta
* [x] 定期更新 Image 并清理旧的 Image
* [x] 同步失败后重试: #5 
* [x] 同步完成后执行外部程序

低优先级:
* [x] 用户认证、~~Fingerprint~~
* [x] Session
* [ ] 使用 Swagger 来生成 API 文档: #10 
* [ ] 完善测试

不确定:
* [ ] ~~限制一次同步的最长时间: #6 （同步结束后容器会被删除，可能会掩盖同步过程中的问题）~~

**Comment by gaoyifan** [comment]
趁这次重构，正好可以实现多个节点共享同一个数据库的功能？

**Comment by knight42** [comment]
如果只是共享数据库的话，感觉只是 MongoDB 的设置问题。

**Comment by gaoyifan** [comment]
虽然数据库是共享的，不过也只有配置部分可以共享。 包括“最后一次同步状态”，“最近同步时间” 等信息 应该都是分开存储的。   我觉得似乎不能单纯依靠设置 MongoDB 来实现。

我感觉多机远比单机要复杂：
1. 如果在 mirror-a 上执行了 import / repo-update / ... ，如何让 mirror-b 也生效
2. 两台机器的同步逻辑：
  - 独立地向上游同步 *（如果部分节点同步失败，则可能导致节点间数据不一致，从而遇到清华的问题https://github.com/tuna/issues/issues/232 ）*
  - 主节点同步后，通知从节点从主节点同步 *（相对比较好的方案）*
3. 允许某些 post_sync 脚本只执行一次。（如果两台机器都各自执行一次推送逻辑，下游源就会执行两次同步）

上面的问题也只是抛砖引玉啦😆
