### ISSUE TITLE
配置文件与 git 更好的结合

### ISSUE THREAD

**Issue by zhsj** [ustclug/Yuki#17]
现在大家操作 yuki 命令后，就直接更改了后端数据库，后面想知道谁改了什么就不方便了。

所以建议：

1. yuki 从文本文件读取配置
2. 操作人员编辑该文本文件，进行 git commit
3. yuki 监控到有新的 commit，重新 reload

**Comment by knight42** [comment]
现在把配置存在数据库里主要是因为通过数据库做 CRUD 很方便，未来如果想加入带过滤条件的查询的话，文本配置文件相对来说就不太好做。

如果只是想知道谁做了哪些改动的话，其实现在理论上是能做到的，只要做日志里记下访问相关 API 的用户就行。

**Comment by zhsj** [comment]
>如果只是想知道谁做了哪些改动的话，其实现在理论上是能做到的，只要做日志里记下访问相关 API 的用户就行。

只知道谁做了什么是没有意义的，是谁为什么做了什么。
