### ISSUE TITLE
为 yukid 添加设置启动的容器中 /tmp 挂载到 tmpfs 的功能

### ISSUE THREAD

**Issue by taoky** [ustclug/Yuki#23]
在新的镜像站机器上配置了 Docker 容器运行时的文件放置到单独的挂载点上（目前分配了 8G 空间），但是在运行时发现有些同步的容器会把很多数据放在 `/tmp` 里面（比如说 Fedora 同步会放置将近 3G 的数据在里面），而默认容器中 `/tmp` 没有单独的挂载点，会占用磁盘空间。

尽管可以扩容，但是或许在 `yukid` 设置里添加 [tmpfs mount](https://docs.docker.com/storage/tmpfs/) 的设定会更好一些？

**Comment by knight42** [comment]
听起来似乎可以把主机的 `/tmp` 挂到容器里？如果可以的话可以参考下这里的配置 https://github.com/ustclug/Yuki/blob/master/cmd/yukid/README.md#repo-configuration 的 `volumes` 字段

**Comment by gaoyifan** [comment]
如果 tmpfs 成为全局行为， 多个依赖 /tmp 的同步程序都会从中受益，减少 IO 开销。如 fedora, freebsd-pkg/ports, homebrew-bottles ...
