### ISSUE TITLE
createdAt 数据异常

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/Yuki#28]
目前的程序逻辑下，创建时间和更新时间始终相等，即 `createdAt === updatedAt`

复现： `yukictl repo ls <repo_name>`

**Comment by knight42** [comment]
确实，现在更新 repo 是通过先删除再添加来实现的，应该可以通过 upsert 来更新。

**Comment by taoky** [comment]
看起来现在已经是 upsert 更新的了。
