### ISSUE TITLE
Connection Refused when using Docker

### ISSUE THREAD

**Issue by kzsyestan** [ustclug/Yuki#70]
我想使用yuki来搭建本地镜像站，但是在使用这个命令时出现了问题
```bash
# The repository directory must be created in advance
mkdir /tmp/repo-data/docker-ce

# Sync docker-ce repository from rsync.mirrors.ustc.edu.cn
cat <<EOF > /tmp/repo-configs/docker-ce.yaml
name: docker-ce
# every 1 hour
cron: "0 * * * *"
storageDir: /tmp/repo-data/docker-ce
image: ustcmirror/rsync:latest
logRotCycle: 2
envs:
  RSYNC_HOST: rsync.mirrors.ustc.edu.cn
  RSYNC_PATH: docker-ce/
  RSYNC_EXCLUDE: --exclude=.~tmp~/
  RSYNC_EXTRA: --size-only
  RSYNC_MAXDELETE: "50000"
EOF

yukictl reload
# Verify
yukictl repo ls

# Trigger synchronization immediately
yukictl sync docker-ce
```
错误提示
```bash
Error: Post "http://127.0.0.1:9999/api/v1/repos": dial tcp 127.0.0.1:9999: connect: connection refused
Error: Get "http://127.0.0.1:9999/api/v1/repos": dial tcp 127.0.0.1:9999: connect: connection refused
Error: Post "http://127.0.0.1:9999/api/v1/repos/docker-ce/sync": dial tcp 127.0.0.1:9999: connect: connection refused
```

我在CSDN查了一些有关的问题也试了一下，但是每次reboot时候都不成功，求教各位大佬！谢谢！

操作系统：**ZorinOS 17.1 Pro - Powered by Ubuntu 22.04 LTS**

**Comment by kzsyestan** [comment]
![截图 2024-05-12 23-45-51](https://github.com/ustclug/Yuki/assets/114994536/ae4f0f02-5f59-44a0-928f-af8dcaaa59d0)
当时截图

**Comment by taoky** [comment]
9999 是 yukid 的端口，在执行 yukictl 的时候 yukid 是否已经启动？

**Comment by taoky** [comment]
请贴一下 /etc/yuki/daemon.toml 的内容。

**Comment by kzsyestan** [comment]
```
db_url = "/tmp/yukid.db"
# uid:gid
owner = "1001:1001"
repo_logs_dir = "/tmp/repo-logs/"
repo_config_dir = "/tmp/repo-configs/"
```
难道说是因为/tmp文件夹中所指向的内容在重启时候被系统清除了？

**Comment by taoky** [comment]
请检查 `/tmp/repo-logs/` 和 `/tmp/repo-configs/` 是否存在。

> 难道说是因为/tmp文件夹中所指向的内容在重启时候被系统清除了？

`/tmp` 是否清理根据系统设置的不同而定，但是 `/tmp` 目录本就不应该存放需要持久保存的文件，这是 FHS（Filesystem Hierarchy Standard）的常识（[hier.7](https://man7.org/linux/man-pages/man7/hier.7.html)）：

> /tmp   This directory contains temporary files which **may be deleted with no notice**, such as by a regular job or at system boot up.

**Comment by kzsyestan** [comment]
刚刚检查过了：确实是没有了，我的/tmp目录里全部是systemd的进程文件和nvim.root。我根据情况改了一下指向的文件夹，可以正常使用。只是这个主机存储太小（150GB），无法同步USTC的Mirrors，我决定将yuki移植到云服务器上使用。感谢指点！
