### ISSUE TITLE
请问freebsd-pkg是如何同步的？

### ISSUE THREAD

**Issue by 89ao** [ustclug/Yuki#79]
看了下，freebsd-pkg好像没有对外提供rsync的同步方式，想请问下咱们ustc的同学，freebsd-pkg的仓库是如何同步到本地的呢？

**Comment by taoky** [comment]
> 看了下，freebsd-pkg好像没有对外提供rsync的同步方式

是有的：rsync://rsync.mirrors.ustc.edu.cn/freebsd-pkg/

> 想请问下咱们ustc的同学，freebsd-pkg的仓库是如何同步到本地的呢？

https://github.com/ustclug/ustcmirror-images/tree/master/freebsd-pkg => [ustcmirror/freebsd-pkg](https://hub.docker.com/r/ustcmirror/freebsd-pkg)
